### ISSUE TITLE
Slide Mount Potentiometer Type

### ISSUE THREAD

**Issue by hitchhiker4200** [InconsolableCellist/LucidVR-EasyPrint#1]
Hello and thanks so much for these designs!  I did have a bit of confusion regarding the Slide Mount and the type of potentiometer it was intended for.  

You have indicated in the description that it replaces the GreenPotSLideHolder_Proto4.1.STL from the LucidGloves repository, but it appears to be designed to replace the larger WLPotSlideHolder_Proto4.1.STL.  It took me a few minutes to figure this out, and since I have the green pots ordered, I'll probably pick up your design and modify it.

Just thought I would let you know.

Thanks again!

**Comment by InconsolableCellist** [comment]
Whoops, you're right. I updated the README to fix those names. I wasn't able to get the greenpots so I only used the larger ones, "WL Pots."

It'd be awesome if you modify it for the green pots! Just make a PR when you can. Also let me know if the design works for you.

The LucidVR design in general still has lots of room for improvement. I haven't been able to make a glove that's reliable or sturdy enough for actual VR use rather than a proof of concept.
